### PR TITLE
fix(grpc): drop stale WatchLoadUpdateReq piggyback, bump sglang floor to 0.5.13

### PR DESCRIPTION
**Pull request by junliu-mde**
### Problem

sglang PR [sgl-project/sglang#28408](https://github.com/sgl-project/sglang/pull/28408) (released in **v0.5.14**) removed `WatchLoadUpdateReq` from `sglang.srt.managers.io_struct` and the `.load` piggyback field from `BatchTokenIDOutput` / `BatchStrOutput`.

`smg-grpc-servicer`'s gRPC request manager still imported `WatchLoadUpdateReq` and forwarded `batch_out.load` to the scheduler on the output streaming hot path. As a result, importing `smg_grpc_servicer.sglang` against sglang ≥ 0.5.14 fails at import time:

```
ImportError: cannot import name 'WatchLoadUpdateReq' from 'sglang.srt.managers.io_struct'
```

This makes gRPC mode entirely unusable on sglang 0.5.14+ — reported in [sgl-project/sglang#28408 (comment)](https://github.com/sgl-project/sglang/pull/28408#issuecomment-4810505329); @ShangmingCai confirmed the interface is deprecated and the fix belongs in smg ([comment](https://github.com/sgl-project/sglang/pull/28408#issuecomment-4815316149)).

### Solution

Drop the stale piggyback path and align the supported sglang range with the shared-memory load-snapshot era.

The piggyback was the DP load feed only on the pre-shmem releases; on every release smg will support after this PR it is dead code:

| sglang release | piggyback present | shmem load snapshots (#26348) | DP load source |
|---|---|---|---|
| 0.5.10 – 0.5.12 | yes | no | piggyback (only feed) |
| 0.5.13 / .post1 | yes | yes | shmem (piggyback has no consumer) |
| 0.5.14+ | **removed** | yes | shmem |

DP load balancing is unaffected on supported releases: both ends of the shmem link live inside sglang, which smg launches unchanged — the writer is `scheduler.py` (`load_snapshot_writer`), the reader is `data_parallel_controller.py` (`load_snapshot_reader.read_all()`). smg's `request_manager` only replaces `TokenizerManager` and was never on the load path once shmem landed. `/v1/loads` (smg's `get_loads`) keeps working on 0.5.13+ via the `GetLoadsReqInput` request/response path the scheduler still serves (`scheduler.py` `handle_get_loads_req`), which I verified remains present in v0.5.14.

## Changes

- `request_manager.py`: remove the `WatchLoadUpdateReq` import and the dead load-forwarding block in `_handle_batch_output`.
- `pyproject.toml`: bump `sglang` floor `0.5.10` → `0.5.13`.

## Test Plan

- `ruff check` + `ruff format --check` on changed file — pass.
- `python -m pytest grpc_servicer/tests` — `20 passed, 6 skipped`.
- Against sglang **0.5.14**: `import smg_grpc_servicer.sglang.request_manager` now imports cleanly (was `ImportError`).
- Against sglang **0.5.13** with `dp_size>1`, `load-balance-method: total_tokens`: DP balancing still distributes across ranks (shmem, no regression).

<details>
<summary>Checklist</summary>

- [x] `ruff check` / `ruff format --check` pass on changed Python (no Rust changes in this PR)
- [x] `python -m pytest grpc_servicer/tests` passes (20 passed, 6 skipped)
- [x] Conventional commit + DCO sign-off, no AI attribution
- [x] (Optional) Documentation updated — N/A (dependency-floor + dead-code removal)

</details>

Refs: sgl-project/sglang#28408

### CODE REVIEW

File: grpc_servicer/pyproject.toml [hunk 1]
```diff
@@ -31,7 +31,9 @@ classifiers = [
 
 [project.optional-dependencies]
 vllm = ["vllm>=0.19.0", "pyzmq>=25.0.0", "msgspec>=0.18.0"]
-sglang = ["sglang>=0.5.10"]
+# 0.5.13 is the first release with the shmem load snapshots that replaced
+# the WatchLoadUpdateReq piggyback path (removed upstream in v0.5.14).
+sglang = ["sglang>=0.5.13"]
```
[the remark this answers is not in the document]
Comment (junliu-mde) [reply grpc_servicer/pyproject.toml:36]: Looks it's better to bump sglang version in CI?

**Review by ShangmingCai — COMMENTED** [review]
Thank you for the fix. The change looks good to me.
